## Initializing Different Types of Arrays


In [3]:
import numpy as np

In [79]:
a = ([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]


In [76]:
# All 0s matrix
np.zeros((2,4,2,7))

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]]])

In [61]:
# All 1s matrix
np.ones((3,3,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [110]:
np.ones((2,2,3,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [57]:
# Any other number
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [95]:
# Any other number (like other existing array shape)
np.full_like(a, 3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [89]:
# Random decimal numbers (V1)
np.random.rand(2,3)

array([[0.97291706, 0.14021583, 0.26044547],
       [0.13373844, 0.74340148, 0.24007013]])

In [90]:
# Random decimal numbers (V2)
np.random.random((2,3))

array([[0.12369965, 0.12570369, 0.03015141],
       [0.08854992, 0.90292313, 0.01608829]])

In [100]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[4, 6, 2],
       [5, 4, 5],
       [2, 6, 1]])

In [103]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


## Build this picture

#### 1 1 1 1 1
#### 1 0 0 0 1
#### 1 0 9 0 1
#### 1 0 0 0 1
#### 1 1 1 1 1

In [138]:
b = np.full((5,5),1)
print(b)
b[1:4, 1:4] = 0
b[2,2] = 9
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [139]:
output = np.full((5,5), 1)
print(output)

z = np.full((3,3),0)
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
