## Mathematics

In [90]:
import numpy as np
import sys

In [19]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [17]:
a + 2

array([17, 18, 19, 20])

In [6]:
a - 2

array([-1,  0,  1,  2])

In [8]:
a * 2

array([2, 4, 6, 8])

In [9]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [24]:
a ** 2

array([ 1,  4,  9, 16])

In [23]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [25]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [31]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [32]:
# Find the determination
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [33]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.min(stats)

1

In [41]:
np.max(stats, axis = 1)

array([3, 6])

In [48]:
np.sum(stats)

21

In [47]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [46]:
np.sum(stats, axis = 1)

array([ 6, 15])


### Reorganizing Arrays

In [53]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# Vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [93]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2,h1])

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

### Miscellaneous

#### Load Data from File

In [92]:
np.genfromtxt("data.txt", delimiter = ',')

OSError: data.txt not found.

In [82]:
filedata = np.array([[1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5],[3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12],[1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88]])
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [74]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [75]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [76]:
# Index fith a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[2,3,5,8]]

array([3, 4, 6, 9])

In [83]:
# Find if any value in "filedata" is > 50
# axis = None - checks all the array at ones
# axis = 1 - checks all the rows
# axis = 0 - checks all the coulumns
np.any(filedata >50, axis = None)

True

In [84]:
# Multiple conditions
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [88]:
filedata[((filedata > 50) & (filedata < 100))]

array([75, 75, 55, 78, 76, 88], dtype=int32)

In [94]:
# Conditions with ~'NOT' statement
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [89]:
filedata[(~((filedata > 50) & (filedata < 100)))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1], dtype=int32)