## Load in NumPy

In [2]:
import numpy as np

## The Basics 

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
a.ndim

1

In [11]:
# Get Shape
b.shape

(2, 3)

In [12]:
# Get Type
a.dtype

dtype('int64')

In [13]:
# Get Size
b.itemsize

8

In [14]:
# Get Total size
a.nbytes

24

### Accessing/Changing specific elements, rows, colums, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# Get specific element [r, c]
a[1, 5]

13

In [17]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get specific column
a[:,3]

array([ 4, 11])

In [24]:
# Get s little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])

[2 4 6]


In [31]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [32]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
# Get specific element (work outside in)
b[0,1,1]

4

In [34]:
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(y)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [39]:
y[2,1,0]

11

In [40]:
y[:,:,1]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [45]:
y[2,1,0],y[1,1,1]

(11, 8)